server.port=8080
server.servlet.context-path=/api

spring.application.name=search-aggregator
spring.jackson.mapper.sort-properties-alphabetically=false

springdoc.swagger-ui.tryItOutEnabled=true

# set to true to use specific endpoints registered on node-endpoints.json
node.endpoints.manual-config=false
node.registry.url=https://node-devel.eosc.grnet.gr/federation-backend/tenants/eosc-beyond/nodes
node.registry.key=