server.port=8080
server.servlet.context-path=/api

spring.application.name=search-aggregator
spring.jackson.mapper.sort-properties-alphabetically=false

springdoc.swagger-ui.tryItOutEnabled=true


# Reciprocal Rank Fusion (RRF) smoothing constant.
# Low values (10-20) aggressively favor top-ranked results from each node.
# High values (60+) favor consensus and dampen the advantage of the #1 rank.
# Since the default fetch quantity is 10 results per node, a value of 20 is recommended.
scoring.rrf.k=20


# set to true to use specific endpoints registered on node-endpoints.json
node.endpoints.manual-config=false
node.registry.url=https://node-devel.eosc.grnet.gr/federation-backend/tenants/eosc-beyond/nodes
node.registry.key=